# Generated by Django 3.0.1 on 2020-07-20 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, default='', max_length=20)),
                ('bio', models.CharField(blank=True, default='', max_length=300)),
                ('avatar', models.ImageField(blank=True, default='', upload_to='avatars')),
                ('birthday', models.DateField(blank=True, default='1990-12-01')),
                ('website', models.CharField(blank=True, default='', max_length=256)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='choose your gender', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm', multiselectfield.db.fields.MultiSelectField(choices=[('music', 'Music'), ('photography', 'Photography'), ('acting', 'Acting'), ('art', 'Acting'), ('travel', 'Travel'), ('sports', 'Sports'), ('humanity', 'Humanity'), ('dance', 'Dance')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
